/**
 * ARENCON FRT v2 — AI Writing Assistant
 * ══════════════════════════════════════
 * 
 * Collects text fields from FRT data model, sends to Cloudflare Worker
 * proxy → Anthropic API, shows review panel with diff view.
 * 
 * Modes:
 *   - 'rewrite' → Full rewrite using Sonnet (professional report language)
 *   - 'quickfix' → Quick fix using Haiku (typos & grammar only)
 */

import { Model } from '../data/model.js';
import { toast } from '../shared/toast.js';

var WORKER_URL = 'https://arencon-ai-worker.hezhendong999.workers.dev';
var _panel = null;
var _overlay = null;
var _suggestions = [];
var _fieldMap = {};
var _processed = 0;
var _accepted = 0;
var _busy = false;

function _esc(s) { return (s || '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;'); }

// ── Field Collection ────────────────────────────────────
function _collectFields() {
  var fields = [];
  _fieldMap = {};
  var p = Model.getProject();
  if (!p) return fields;
  var minLen = 8;

  // Contractor deficiencies
  (p.contractors || []).forEach(function(c, ci) {
    (c.deficiencies || []).forEach(function(d, di) {
      var dLabel = (c.name || 'General') + ' \u2192 #' + (d.num || '?');
      (d.observations || []).forEach(function(o, oi) {
        if (o.text && o.text.trim().length >= minLen) {
          var fid = 'c' + ci + '_d' + di + '_o' + oi;
          fields.push({ id: fid, label: dLabel + ' \u2192 Obs ' + (oi + 1), text: o.text.trim() });
          _fieldMap[fid] = { path: [ci, di, 'obs', oi], original: o.text.trim(), label: dLabel + ' \u2192 Obs ' + (oi + 1) };
        }
      });
      (d.activity || []).forEach(function(a, ai) {
        if (a.text && a.text.trim().length >= minLen && !a.autoGenerated) {
          var fid = 'c' + ci + '_d' + di + '_a' + ai;
          var aDate = a.date || '';
          fields.push({ id: fid, label: dLabel + ' \u2192 Activity ' + (aDate || (ai + 1)), text: a.text.trim() });
          _fieldMap[fid] = { path: [ci, di, 'act', ai], original: a.text.trim(), label: dLabel + ' \u2192 Activity ' + (aDate || (ai + 1)) };
        }
      });
      if (d.closedNote && d.closedNote.trim().length >= minLen) {
        var fid = 'c' + ci + '_d' + di + '_cn';
        fields.push({ id: fid, label: dLabel + ' \u2192 Closed Note', text: d.closedNote.trim() });
        _fieldMap[fid] = { path: [ci, di, 'cn', 0], original: d.closedNote.trim(), label: dLabel + ' \u2192 Closed Note' };
      }
    });
  });

  // General deficiencies
  (p.generalDeficiencies || []).forEach(function(d, di) {
    var dLabel = 'Site General \u2192 #' + (d.num || '?');
    (d.observations || []).forEach(function(o, oi) {
      if (o.text && o.text.trim().length >= minLen) {
        var fid = 'g' + di + '_o' + oi;
        fields.push({ id: fid, label: dLabel + ' \u2192 Obs ' + (oi + 1), text: o.text.trim() });
        _fieldMap[fid] = { path: ['gen', di, 'obs', oi], original: o.text.trim(), label: dLabel + ' \u2192 Obs ' + (oi + 1) };
      }
    });
    (d.activity || []).forEach(function(a, ai) {
      if (a.text && a.text.trim().length >= minLen && !a.autoGenerated) {
        var fid = 'g' + di + '_a' + ai;
        fields.push({ id: fid, label: dLabel + ' \u2192 Activity ' + (a.date || (ai + 1)), text: a.text.trim() });
        _fieldMap[fid] = { path: ['gen', di, 'act', ai], original: a.text.trim(), label: dLabel + ' \u2192 Activity ' + (a.date || (ai + 1)) };
      }
    });
  });

  return fields;
}

// ── Word-Level Diff (LCS algorithm) ─────────────────────
function _wordDiff(original, improved) {
  if (original === improved) return { html: _esc(improved), changed: false };
  var a = original.split(/(\s+)/), b = improved.split(/(\s+)/);
  var m = a.length, n = b.length;
  if (m > 200 || n > 200) {
    return { html: '<span class="ai-diff-del">' + _esc(original) + '</span> <span class="ai-diff-add">' + _esc(improved) + '</span>', changed: true };
  }
  var dp = [];
  for (var i = 0; i <= m; i++) { dp[i] = []; for (var j = 0; j <= n; j++) dp[i][j] = 0; }
  for (i = 1; i <= m; i++) for (j = 1; j <= n; j++) {
    if (a[i - 1] === b[j - 1]) dp[i][j] = dp[i - 1][j - 1] + 1;
    else dp[i][j] = Math.max(dp[i - 1][j], dp[i][j - 1]);
  }
  var result = [];
  i = m; j = n;
  while (i > 0 || j > 0) {
    if (i > 0 && j > 0 && a[i - 1] === b[j - 1]) {
      result.unshift({ type: 'same', text: a[i - 1] }); i--; j--;
    } else if (j > 0 && (i === 0 || dp[i][j - 1] >= dp[i - 1][j])) {
      result.unshift({ type: 'add', text: b[j - 1] }); j--;
    } else {
      result.unshift({ type: 'del', text: a[i - 1] }); i--;
    }
  }
  var html = '';
  result.forEach(function(r) {
    if (r.type === 'same') html += _esc(r.text);
    else if (r.type === 'add') html += '<span class="ai-diff-add">' + _esc(r.text) + '</span>';
    else html += '<span class="ai-diff-del">' + _esc(r.text) + '</span>';
  });
  return { html: html, changed: true };
}

// ── Panel UI ────────────────────────────────────────────
function _ensurePanel() {
  if (_panel) return;
  _overlay = document.createElement('div');
  _overlay.className = 'ai-panel-overlay';
  _overlay.addEventListener('click', function() { _closePanel(); });
  document.body.appendChild(_overlay);

  _panel = document.createElement('div');
  _panel.className = 'ai-panel';
  _panel.addEventListener('click', function(e) { e.stopPropagation(); });
  _panel.innerHTML = '<div class="ai-panel-hdr"><h3>\u2728 AI Review</h3><div class="ai-panel-hdr-btns">'
    + '<button class="ai-btn-accept-all" id="ai-accept-all"style="background:#1A7A4A;color:white;">Accept All</button>'
    + '<button class="ai-btn-close" style="background:rgba(255,255,255,.15);color:white;">\u2715</button>'
    + '</div></div>'
    + '<div class="ai-panel-counter" id="ai-counter"></div>'
    + '<div class="ai-panel-body" id="ai-body"></div>';
  document.body.appendChild(_panel);

  // Wire panel buttons
  _panel.querySelector('.ai-btn-close').addEventListener('click', _closePanel);
  _panel.querySelector('#ai-accept-all').addEventListener('click', _acceptAll);
}

function _openPanel() {
  _ensurePanel();
  requestAnimationFrame(function() {
    _overlay.classList.add('open');
    _panel.classList.add('open');
  });
}

function _closePanel() {
  if (_overlay) _overlay.classList.remove('open');
  if (_panel) _panel.classList.remove('open');
  if (_accepted > 0) {
    Model.saveNow();
    Model._notify('project', Model.getProject());
  }
  _busy = false;
  _updateBtn(false);
}

function _updateCounter() {
  var el = document.getElementById('ai-counter');
  if (!el) return;
  var total = _suggestions.length;
  var remaining = total - _processed;
  if (remaining <= 0) el.textContent = '\u2714 All done \u2014 ' + _accepted + ' accepted, ' + (total - _accepted) + ' skipped';
  else el.textContent = (_processed + 1) + ' of ' + total + ' suggestions';
}

function _renderSuggestions(suggestions) {
  _suggestions = suggestions.filter(function(s) {
    var fm = _fieldMap[s.id];
    return fm && s.improved && s.improved !== fm.original;
  });
  _processed = 0;
  _accepted = 0;
  var body = document.getElementById('ai-body');
  if (!body) return;
  body.innerHTML = '';
  if (_suggestions.length === 0) {
    body.innerHTML = '<div class="ai-panel-done">\u2714 All text looks good \u2014 no suggestions</div>';
    _updateCounter();
    var aaBtn = document.getElementById('ai-accept-all');
    if (aaBtn) aaBtn.style.display = 'none';
    setTimeout(function() { _closePanel(); }, 3000);
    return;
  }
  var aaBtn2 = document.getElementById('ai-accept-all');
  if (aaBtn2) aaBtn2.style.display = '';

  _suggestions.forEach(function(s, idx) {
    var fm = _fieldMap[s.id];
    if (!fm) return;
    var diff = _wordDiff(fm.original, s.improved);
    var div = document.createElement('div');
    div.className = 'ai-suggestion';
    div.id = 'ai-sug-' + idx;
    div.innerHTML = '<div class="ai-field-label">' + _esc(fm.label) + '</div>'
      + '<div class="ai-text-box-label">Original</div>'
      + '<div class="ai-text-box">' + _esc(fm.original) + '</div>'
      + '<div class="ai-text-box-label">Suggested</div>'
      + '<div class="ai-text-box">' + diff.html + '</div>'
      + (s.changes && s.changes !== 'no changes needed' ? '<div class="ai-changes-note">' + _esc(s.changes) + '</div>' : '')
      + '<div class="ai-suggestion-btns">'
      + '<button class="ai-btn-accept" data-sug-idx="' + idx + '">Accept</button>'
      + '<button class="ai-btn-skip" data-sug-idx="' + idx + '">Skip</button>'
      + '</div>';
    body.appendChild(div);
  });

  // Delegate accept/skip clicks
  body.addEventListener('click', function(e) {
    var btn = e.target.closest && e.target.closest('[data-sug-idx]');
    if (!btn) return;
    var idx = parseInt(btn.getAttribute('data-sug-idx'));
    if (btn.classList.contains('ai-btn-accept')) _accept(idx);
    else if (btn.classList.contains('ai-btn-skip')) _skip(idx);
  });

  _updateCounter();
}

// ── Accept / Skip / Accept All ──────────────────────────
function _accept(idx) {
  var s = _suggestions[idx];
  if (!s) return;
  var fm = _fieldMap[s.id];
  if (!fm) return;
  _writeBack(fm.path, s.improved);
  Model.saveNow();
  var el = document.getElementById('ai-sug-' + idx);
  if (el) {
    el.classList.add('processed');
    var btns = el.querySelector('.ai-suggestion-btns');
    if (btns) btns.innerHTML = '<span style="color:#1A7A4A;font-weight:600;">\u2714 Accepted</span>';
  }
  _processed++;
  _accepted++;
  _updateCounter();
  _scrollToNext(idx);
  if (_processed >= _suggestions.length) _finishReview();
}

function _skip(idx) {
  var el = document.getElementById('ai-sug-' + idx);
  if (el) {
    el.classList.add('processed');
    var btns = el.querySelector('.ai-suggestion-btns');
    if (btns) btns.innerHTML = '<span style="color:#6B7280;">Skipped</span>';
  }
  _processed++;
  _updateCounter();
  _scrollToNext(idx);
  if (_processed >= _suggestions.length) _finishReview();
}

function _acceptAll() {
  _suggestions.forEach(function(s, idx) {
    var el = document.getElementById('ai-sug-' + idx);
    if (el && !el.classList.contains('processed')) _accept(idx);
  });
}

function _scrollToNext(currentIdx) {
  for (var i = currentIdx + 1; i < _suggestions.length; i++) {
    var el = document.getElementById('ai-sug-' + i);
    if (el && !el.classList.contains('processed')) {
      el.scrollIntoView({ behavior: 'smooth', block: 'start' });
      return;
    }
  }
}

function _finishReview() {
  if (_accepted > 0) {
    Model.saveNow();
    Model._notify('project', Model.getProject());
  }
  _updateCounter();
  setTimeout(function() { _closePanel(); }, 2500);
}

// ── Write-Back to Data Model ────────────────────────────
function _writeBack(path, newText) {
  var p = Model.getProject();
  if (!p) return;
  var ci = path[0], di = path[1], type = path[2], idx = path[3];
  var deficArr;
  if (ci === 'gen') {
    deficArr = p.generalDeficiencies;
  } else {
    if (!p.contractors || !p.contractors[ci]) return;
    deficArr = p.contractors[ci].deficiencies;
  }
  if (!deficArr || !deficArr[di]) return;
  var d = deficArr[di];
  if (type === 'obs') {
    if (d.observations && d.observations[idx]) d.observations[idx].text = newText;
    if (d.entries && d.entries[idx]) { d.entries[idx].text = newText; d.entries[idx].description = newText; }
    if (idx === 0) d.description = newText;
  } else if (type === 'act') {
    if (d.activity && d.activity[idx]) d.activity[idx].text = newText;
  } else if (type === 'cn') {
    d.closedNote = newText;
  }
}

// ── Button State ────────────────────────────────────────
function _updateBtn(busy, mode) {
  var btn = document.getElementById('btn-ai-review');
  if (!btn) return;
  if (busy) {
    btn.disabled = true;
    btn.innerHTML = '<span class="ai-spin-icon">\u2728</span> ' + (mode === 'quickfix' ? 'Checking' : 'Rewriting') + '\u2026';
  } else {
    btn.disabled = false;
    btn.innerHTML = '\u2728 AI Review \u25BE';
  }
}

// ── Auth Token ──────────────────────────────────────────
function _getToken() {
  return localStorage.getItem('sb-access-token') || null;
}

// ── Main Entry Point ────────────────────────────────────
function reviewAll(mode) {
  if (_busy) return;
  if (!mode) mode = 'rewrite';
  if (!Model.getProject()) { toast('\u26A0 Open a project first'); return; }
  var token = _getToken();
  if (!token) { toast('\u26A0 AI Review requires cloud login'); return; }
  var fields = _collectFields();
  if (fields.length === 0) { toast('\u2714 No text fields to review'); return; }

  _busy = true;
  _updateBtn(true, mode);
  _openPanel();

  var body = document.getElementById('ai-body');
  var modeLabel = mode === 'quickfix' ? 'Quick Fix (Haiku)' : 'Full Rewrite (Sonnet)';
  if (body) body.innerHTML = '<div class="ai-panel-loading"><div class="ai-spinner"></div><br>' + modeLabel + '<br>Reviewing ' + fields.length + ' field' + (fields.length !== 1 ? 's' : '') + '\u2026</div>';
  var aaBtn = document.getElementById('ai-accept-all');
  if (aaBtn) aaBtn.style.display = 'none';
  var ctr = document.getElementById('ai-counter');
  if (ctr) ctr.textContent = modeLabel + ' \u2014 Sending\u2026';

  var p = Model.getProject();
  var context = {
    tool: 'frt',
    projectNumber: (p.info && p.info.projectNumber) || '',
    projectName: (p.info && p.info.projectName) || ''
  };

  fetch(WORKER_URL, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'Authorization': 'Bearer ' + token },
    body: JSON.stringify({ fields: fields, context: context, mode: mode })
  })
  .then(function(res) {
    if (!res.ok) return res.json().then(function(e) { throw new Error(e.error || 'API error ' + res.status); });
    return res.json();
  })
  .then(function(data) {
    _busy = false;
    _updateBtn(false);
    if (!data.suggestions || !Array.isArray(data.suggestions)) {
      throw new Error('Invalid response from AI');
    }
    _renderSuggestions(data.suggestions);
    if (data.usage && data.usage.cost_usd !== undefined) {
      var ctr2 = document.getElementById('ai-counter');
      if (ctr2) ctr2.textContent += (' \u00B7 Cost: $' + data.usage.cost_usd.toFixed(4));
    }
  })
  .catch(function(err) {
    _busy = false;
    _updateBtn(false);
    console.error('[AIAssist] Error:', err);
    var body2 = document.getElementById('ai-body');
    if (body2) body2.innerHTML = '<div class="ai-panel-loading" style="color:#C62828;">\u26A0 ' + _esc(err.message || 'Failed to connect to AI service') + '<br><br><button class="ai-btn-skip" style="border:1.5px solid #6B7280!important;padding:8px 16px;border-radius:6px;cursor:pointer;font-family:Calibri,sans-serif;">Close</button></div>';
    if (body2) body2.querySelector('.ai-btn-skip').addEventListener('click', _closePanel);
    var ctr3 = document.getElementById('ai-counter');
    if (ctr3) ctr3.textContent = 'Error';
  });
}

// ── Dropdown Menu ───────────────────────────────────────
function _toggleMenu() {
  var m = document.getElementById('ai-mode-menu');
  if (m) m.classList.toggle('open');
}
function _closeMenu() {
  var m = document.getElementById('ai-mode-menu');
  if (m) m.classList.remove('open');
}

// ── Public API ──────────────────────────────────────────
export var AIAssist = {
  reviewAll: reviewAll,
  _toggleMenu: _toggleMenu,
  _closeMenu: _closeMenu
};

// Global access for onclick in HTML
window.AIAssist = AIAssist;
