/**
 * ARENCON FRT v2 — AI Writing Assistant
 * ══════════════════════════════════════
 * 
 * Collects text fields from FRT data model, sends to Cloudflare Worker
 * proxy → Anthropic API, shows review panel with diff view.
 * 
 * Modes:
 *   - 'rewrite' → Full rewrite using Sonnet (professional report language)
 *   - 'quickfix' → Quick fix using Haiku (typos & grammar only)
 */

import { Model } from '../data/model.js';
import { toast } from '../shared/toast.js';

var WORKER_URL = 'https://arencon-ai-worker.hezhendong999.workers.dev';
var _panel = null;
var _overlay = null;
var _suggestions = [];
var _fieldMap = {};
var _processed = 0;
var _accepted = 0;
var _busy = false;

function _esc(s) { return (s || '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;'); }

// ── Field Collection ────────────────────────────────────
function _collectFields() {
  var fields = [];
  _fieldMap = {};
  var p = Model.getProject();
  if (!p) return fields;
  var minLen = 8;

  // Contractor deficiencies
  (p.contractors || []).forEach(function(c, ci) {
    (c.deficiencies || []).forEach(function(d, di) {
      var dLabel = (c.name || 'General') + ' \u2192 #' + (d.num || '?');
      (d.observations || []).forEach(function(o, oi) {
        if (o.text && o.text.trim().length >= minLen) {
          var fid = 'c' + ci + '_d' + di + '_o' + oi;
          fields.push({ id: fid, label: dLabel + ' \u2192 Obs ' + (oi + 1), text: o.text.trim() });
          _fieldMap[fid] = { path: [ci, di, 'obs', oi], original: o.text.trim(), label: dLabel + ' \u2192 Obs ' + (oi + 1) };
        }
      });
      (d.activity || []).forEach(function(a, ai) {
        if (a.text && a.text.trim().length >= minLen && !a.autoGenerated) {
          var fid = 'c' + ci + '_d' + di + '_a' + ai;
          var aDate = a.date || '';
          fields.push({ id: fid, label: dLabel + ' \u2192 Activity ' + (aDate || (ai + 1)), text: a.text.trim() });
          _fieldMap[fid] = { path: [ci, di, 'act', ai], original: a.text.trim(), label: dLabel + ' \u2192 Activity ' + (aDate || (ai + 1)) };
        }
      });
      if (d.closedNote && d.closedNote.trim().length >= minLen) {
        var fid = 'c' + ci + '_d' + di + '_cn';
        fields.push({ id: fid, label: dLabel + ' \u2192 Closed Note', text: d.closedNote.trim() });
        _fieldMap[fid] = { path: [ci, di, 'cn', 0], original: d.closedNote.trim(), label: dLabel + ' \u2192 Closed Note' };
      }
    });
  });

  // General deficiencies
  (p.generalDeficiencies || []).forEach(function(d, di) {
    var dLabel = 'Site General \u2192 #' + (d.num || '?');
    (d.observations || []).forEach(function(o, oi) {
      if (o.text && o.text.trim().length >= minLen) {
        var fid = 'g' + di + '_o' + oi;
        fields.push({ id: fid, label: dLabel + ' \u2192 Obs ' + (oi + 1), text: o.text.trim() });
        _fieldMap[fid] = { path: ['gen', di, 'obs', oi], original: o.text.trim(), label: dLabel + ' \u2192 Obs ' + (oi + 1) };
      }
    });
    (d.activity || []).forEach(function(a, ai) {
      if (a.text && a.text.trim().length >= minLen && !a.autoGenerated) {
        var fid = 'g' + di + '_a' + ai;
        fields.push({ id: fid, label: dLabel + ' \u2192 Activity ' + (a.date || (ai + 1)), text: a.text.trim() });
        _fieldMap[fid] = { path: ['gen', di, 'act', ai], original: a.text.trim(), label: dLabel + ' \u2192 Activity ' + (a.date || (ai + 1)) };
      }
    });
  });

  return fields;
}

// ── Word-Level Diff (LCS algorithm) ─────────────────────
function _wordDiff(original, improved) {
  if (original === improved) return { html: _esc(improved), changed: false };
  var a = original.split(/(\s+)/), b = improved.split(/(\s+)/);
  var m = a.length, n = b.length;
  if (m > 200 || n > 200) {
    return { html: '<span class="ai-diff-del">' + _esc(original) + '</span> <span class="ai-diff-add">' + _esc(improved) + '</span>', changed: true };
  }
  var dp = [];
  for (var i = 0; i <= m; i++) { dp[i] = []; for (var j = 0; j <= n; j++) dp[i][j] = 0; }
  for (i = 1; i <= m; i++) for (j = 1; j <= n; j++) {
    if (a[i - 1] === b[j - 1]) dp[i][j] = dp[i - 1][j - 1] + 1;
    else dp[i][j] = Math.max(dp[i - 1][j], dp[i][j - 1]);
  }
  var result = [];
  i = m; j = n;
  while (i > 0 || j > 0) {
    if (i > 0 && j > 0 && a[i - 1] === b[j - 1]) {
      result.unshift({ type: 'same', text: a[i - 1] }); i--; j--;
    } else if (j > 0 && (i === 0 || dp[i][j - 1] >= dp[i - 1][j])) {
      result.unshift({ type: 'add', text: b[j - 1] }); j--;
    } else {
      result.unshift({ type: 'del', text: a[i - 1] }); i--;
    }
  }
  var html = '';
  result.forEach(function(r) {
    if (r.type === 'same') html += _esc(r.text);
    else if (r.type === 'add') html += '<span class="ai-diff-add">' + _esc(r.text) + '</span>';
    else html += '<span class="ai-diff-del">' + _esc(r.text) + '</span>';
  });
  return { html: html, changed: true };
}

// ── Panel UI ────────────────────────────────────────────
function _ensurePanel() {
  if (_panel) return;
  _overlay = document.createElement('div');
  _overlay.className = 'ai-panel-overlay';
  _overlay.addEventListener('click', function() { _closePanel(); });
  document.body.appendChild(_overlay);

  _panel = document.createElement('div');
  _panel.className = 'ai-panel';
  _panel.addEventListener('click', function(e) { e.stopPropagation(); });
  _panel.innerHTML = '<div class="ai-panel-hdr"><h3>\u2728 AI Review</h3><div class="ai-panel-hdr-btns">'
    + '<button class="ai-btn-accept-all" id="ai-accept-all"style="background:#1A7A4A;color:white;">Accept All</button>'
    + '<button class="ai-btn-close" style="background:rgba(255,255,255,.15);color:white;">\u2715</button>'
    + '</div></div>'
    + '<div class="ai-panel-counter" id="ai-counter"></div>'
    + '<div class="ai-panel-body" id="ai-body"></div>';
  document.body.appendChild(_panel);

  // Wire panel buttons
  _panel.querySelector('.ai-btn-close').addEventListener('click', _closePanel);
  _panel.querySelector('#ai-accept-all').addEventListener('click', _acceptAll);
}

function _openPanel() {
  _ensurePanel();
  requestAnimationFrame(function() {
    _overlay.classList.add('open');
    _panel.classList.add('open');
  });
}

function _closePanel() {
  if (_overlay) _overlay.classList.remove('open');
  if (_panel) _panel.classList.remove('open');
  if (_accepted > 0) {
    Model.saveNow();
    Model._notify('project', Model.getProject());
  }
  _busy = false;
  _updateBtn(false);
}

function _updateCounter() {
  var el = document.getElementById('ai-counter');
  if (!el) return;
  var total = _suggestions.length;
  var remaining = total - _processed;
  if (remaining <= 0) el.textContent = '\u2714 All done \u2014 ' + _accepted + ' accepted, ' + (total - _accepted) + ' skipped';
  else el.textContent = (_processed + 1) + ' of ' + total + ' suggestions';
}

function _renderSuggestions(suggestions) {
  _suggestions = suggestions.filter(function(s) {
    var fm = _fieldMap[s.id];
    return fm && s.improved && s.improved !== fm.original;
  });
  _processed = 0;
  _accepted = 0;
  var body = document.getElementById('ai-body');
  if (!body) return;
  body.innerHTML = '';
  if (_suggestions.length === 0) {
    body.innerHTML = '<div class="ai-panel-done">\u2714 All text looks good \u2014 no suggestions</div>';
    _updateCounter();
    var aaBtn = document.getElementById('ai-accept-all');
    if (aaBtn) aaBtn.style.display = 'none';
    setTimeout(function() { _closePanel(); }, 3000);
    return;
  }
  var aaBtn2 = document.getElementById('ai-accept-all');
  if (aaBtn2) aaBtn2.style.display = '';

  _suggestions.forEach(function(s, idx) {
    var fm = _fieldMap[s.id];
    if (!fm) return;
    var diff = _wordDiff(fm.original, s.improved);
    var div = document.createElement('div');
    div.className = 'ai-suggestion';
    div.id = 'ai-sug-' + idx;
    div.innerHTML = '<div class="ai-field-label">' + _esc(fm.label) + '</div>'
      + '<div class="ai-text-box-label">Original</div>'
      + '<div class="ai-text-box">' + _esc(fm.original) + '</div>'
      + '<div class="ai-text-box-label">Suggested</div>'
      + '<div class="ai-text-box">' + diff.html + '</div>'
      + (s.changes && s.changes !== 'no changes needed' ? '<div class="ai-changes-note">' + _esc(s.changes) + '</div>' : '')
      + '<div class="ai-suggestion-btns">'
      + '<button class="ai-btn-accept" data-sug-idx="' + idx + '">Accept</button>'
      + '<button class="ai-btn-skip" data-sug-idx="' + idx + '">Skip</button>'
      + '</div>';
    body.appendChild(div);
  });

  // Delegate accept/skip clicks
  body.addEventListener('click', function(e) {
    var btn = e.target.closest && e.target.closest('[data-sug-idx]');
    if (!btn) return;
    var idx = parseInt(btn.getAttribute('data-sug-idx'));
    if (btn.classList.contains('ai-btn-accept')) _accept(idx);
    else if (btn.classList.contains('ai-btn-skip')) _skip(idx);
  });

  _updateCounter();
}

// ── Accept / Skip / Accept All ──────────────────────────
function _accept(idx) {
  var s = _suggestions[idx];
  if (!s) return;
  var fm = _fieldMap[s.id];
  if (!fm) return;
  _writeBack(fm.path, s.improved);
  Model.saveNow();
  var el = document.getElementById('ai-sug-' + idx);
  if (el) {
    el.classList.add('processed');
    var btns = el.querySelector('.ai-suggestion-btns');
    if (btns) btns.innerHTML = '<span style="color:#1A7A4A;font-weight:600;">\u2714 Accepted</span>';
  }
  _processed++;
  _accepted++;
  _updateCounter();
  _scrollToNext(idx);
  if (_processed >= _suggestions.length) _finishReview();
}

function _skip(idx) {
  var el = document.getElementById('ai-sug-' + idx);
  if (el) {
    el.classList.add('processed');
    var btns = el.querySelector('.ai-suggestion-btns');
    if (btns) btns.innerHTML = '<span style="color:#6B7280;">Skipped</span>';
  }
  _processed++;
  _updateCounter();
  _scrollToNext(idx);
  if (_processed >= _suggestions.length) _finishReview();
}

function _acceptAll() {
  _suggestions.forEach(function(s, idx) {
    var el = document.getElementById('ai-sug-' + idx);
    if (el && !el.classList.contains('processed')) _accept(idx);
  });
}

function _scrollToNext(currentIdx) {
  for (var i = currentIdx + 1; i < _suggestions.length; i++) {
    var el = document.getElementById('ai-sug-' + i);
    if (el && !el.classList.contains('processed')) {
      el.scrollIntoView({ behavior: 'smooth', block: 'start' });
      return;
    }
  }
}

function _finishReview() {
  if (_accepted > 0) {
    Model.saveNow();
    Model._notify('project', Model.getProject());
  }
  _updateCounter();
  setTimeout(function() { _closePanel(); }, 2500);
}

// ── Write-Back to Data Model ────────────────────────────
function _writeBack(path, newText) {
  var p = Model.getProject();
  if (!p) return;
  var ci = path[0], di = path[1], type = path[2], idx = path[3];
  var deficArr;
  if (ci === 'gen') {
    deficArr = p.generalDeficiencies;
  } else {
    if (!p.contractors || !p.contractors[ci]) return;
    deficArr = p.contractors[ci].deficiencies;
  }
  if (!deficArr || !deficArr[di]) return;
  var d = deficArr[di];
  if (type === 'obs') {
    if (d.observations && d.observations[idx]) { d.observations[idx].text = newText; d.observations[idx].aiReviewed = true; }
    if (d.entries && d.entries[idx]) { d.entries[idx].text = newText; d.entries[idx].description = newText; }
    if (idx === 0) d.description = newText;
  } else if (type === 'act') {
    if (d.activity && d.activity[idx]) { d.activity[idx].text = newText; d.activity[idx].aiReviewed = true; }
  } else if (type === 'cn') {
    d.closedNote = newText; d.closedNoteAiReviewed = true;
  }
}

// ── Button State ────────────────────────────────────────
function _updateBtn(busy, mode) {
  var btn = document.getElementById('btn-ai-review');
  if (!btn) return;
  if (busy) {
    btn.disabled = true;
    btn.innerHTML = '<span class="ai-spin-icon">\u2728</span> ' + (mode === 'quickfix' ? 'Checking' : 'Rewriting') + '\u2026';
  } else {
    btn.disabled = false;
    btn.innerHTML = '\u2728 AI Review \u25BE';
  }
}

// ── Auth Token ──────────────────────────────────────────
function _getToken() {
  return localStorage.getItem('sb-access-token') || null;
}

// ── Field Selector Modal ────────────────────────────────
function _showFieldSelector(fields, mode) {
  return new Promise(function(resolve) {
    var existing = document.getElementById('ai-fs-overlay');
    if (existing) existing.remove();

    var overlay = document.createElement('div');
    overlay.id = 'ai-fs-overlay';
    overlay.className = 'ai-fs-overlay';

    var modeLabel = mode === 'quickfix' ? 'Quick Fix (Haiku)' : 'Full Rewrite (Sonnet)';

    // Group fields by deficiency for nicer display
    var html = '<div class="ai-fs-modal">';
    html += '<div class="ai-fs-header"><h3>\u2728 AI Review \u2014 Select Fields</h3>';
    html += '<button class="ai-fs-x" title="Cancel">\u2715</button></div>';
    html += '<div class="ai-fs-subhdr"><span class="ai-fs-mode">' + _esc(modeLabel) + '</span>';
    html += '<button class="ai-fs-toggle" data-state="all">Deselect All</button></div>';
    html += '<div class="ai-fs-body">';
    fields.forEach(function(f, i) {
      var text = f.text || '';
      var preview = text.length > 140 ? text.substring(0, 140) + '\u2026' : text;
      html += '<label class="ai-fs-row">';
      html += '<input type="checkbox" class="ai-fs-check" data-idx="' + i + '" checked>';
      html += '<div class="ai-fs-info">';
      html += '<div class="ai-fs-label">' + _esc(f.label) + '</div>';
      html += '<div class="ai-fs-preview">' + _esc(preview) + '</div>';
      html += '</div></label>';
    });
    html += '</div>';
    html += '<div class="ai-fs-footer"><span class="ai-fs-count">' + fields.length + ' of ' + fields.length + ' selected</span>';
    html += '<div class="ai-fs-btns"><button class="ai-fs-confirm">Review \u2192</button>';
    html += '<button class="ai-fs-cancel">Cancel</button></div></div>';
    html += '</div>';
    overlay.innerHTML = html;
    document.body.appendChild(overlay);
    requestAnimationFrame(function() { overlay.classList.add('open'); });

    function updateCount() {
      var checks = overlay.querySelectorAll('.ai-fs-check');
      var cnt = 0;
      for (var i = 0; i < checks.length; i++) if (checks[i].checked) cnt++;
      var span = overlay.querySelector('.ai-fs-count');
      if (span) span.textContent = cnt + ' of ' + fields.length + ' selected';
      var btn = overlay.querySelector('.ai-fs-confirm');
      if (btn) {
        btn.disabled = cnt === 0;
        btn.textContent = 'Review ' + cnt + ' \u2192';
      }
      var toggle = overlay.querySelector('.ai-fs-toggle');
      if (toggle) {
        var allOn = cnt === fields.length;
        toggle.textContent = allOn ? 'Deselect All' : 'Select All';
        toggle.dataset.state = allOn ? 'all' : 'none';
      }
    }

    overlay.addEventListener('change', function(e) {
      if (e.target.classList && e.target.classList.contains('ai-fs-check')) updateCount();
    });

    overlay.querySelector('.ai-fs-toggle').addEventListener('click', function() {
      var checks = overlay.querySelectorAll('.ai-fs-check');
      var allOn = true;
      for (var i = 0; i < checks.length; i++) if (!checks[i].checked) { allOn = false; break; }
      for (var j = 0; j < checks.length; j++) checks[j].checked = !allOn;
      updateCount();
    });

    function cleanup(result) {
      overlay.classList.remove('open');
      setTimeout(function() { overlay.remove(); resolve(result); }, 150);
    }

    overlay.querySelector('.ai-fs-x').addEventListener('click', function() { cleanup(null); });
    overlay.querySelector('.ai-fs-cancel').addEventListener('click', function() { cleanup(null); });
    overlay.querySelector('.ai-fs-confirm').addEventListener('click', function() {
      var selected = [];
      var checks = overlay.querySelectorAll('.ai-fs-check');
      for (var i = 0; i < checks.length; i++) {
        if (checks[i].checked) {
          var idx = parseInt(checks[i].getAttribute('data-idx'), 10);
          selected.push(fields[idx]);
        }
      }
      cleanup(selected.length > 0 ? selected : null);
    });
    updateCount();
  });
}

// ── Main Entry Point ────────────────────────────────────
function reviewAll(mode) {
  if (_busy) return;
  if (!mode) mode = 'rewrite';
  if (!Model.getProject()) { toast('\u26A0 Open a project first'); return; }
  var token = _getToken();
  if (!token) { toast('\u26A0 AI Review requires cloud login'); return; }
  var allFields = _collectFields();
  if (allFields.length === 0) { toast('\u2714 No text fields to review'); return; }

  // Show field selector for >1 field; single field auto-proceeds
  if (allFields.length === 1) {
    _doReview(allFields, mode, token);
    return;
  }
  _showFieldSelector(allFields, mode).then(function(selected) {
    if (!selected || selected.length === 0) return; // cancelled
    _doReview(selected, mode, token);
  });
}

function _doReview(fields, mode, token) {
  _busy = true;
  _updateBtn(true, mode);
  _openPanel();

  var body = document.getElementById('ai-body');
  var modeLabel = mode === 'quickfix' ? 'Quick Fix (Haiku)' : 'Full Rewrite (Sonnet)';
  if (body) body.innerHTML = '<div class="ai-panel-loading"><div class="ai-spinner"></div><br>' + modeLabel + '<br>Reviewing ' + fields.length + ' field' + (fields.length !== 1 ? 's' : '') + '\u2026</div>';
  var aaBtn = document.getElementById('ai-accept-all');
  if (aaBtn) aaBtn.style.display = 'none';
  var ctr = document.getElementById('ai-counter');
  if (ctr) ctr.textContent = modeLabel + ' \u2014 Sending\u2026';

  var p = Model.getProject();
  var context = {
    tool: 'frt',
    projectNumber: (p.info && p.info.projectNumber) || '',
    projectName: (p.info && p.info.projectName) || ''
  };

  fetch(WORKER_URL, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'Authorization': 'Bearer ' + token },
    body: JSON.stringify({ fields: fields, context: context, mode: mode })
  })
  .then(function(res) {
    if (!res.ok) return res.json().then(function(e) { throw new Error(e.error || 'API error ' + res.status); });
    return res.json();
  })
  .then(function(data) {
    _busy = false;
    _updateBtn(false);
    if (!data.suggestions || !Array.isArray(data.suggestions)) {
      throw new Error('Invalid response from AI');
    }
    _renderSuggestions(data.suggestions);
    if (data.usage && data.usage.cost_usd !== undefined) {
      var ctr2 = document.getElementById('ai-counter');
      if (ctr2) ctr2.textContent += (' \u00B7 Cost: $' + data.usage.cost_usd.toFixed(4));
    }
  })
  .catch(function(err) {
    _busy = false;
    _updateBtn(false);
    console.error('[AIAssist] Error:', err);
    var body2 = document.getElementById('ai-body');
    if (body2) body2.innerHTML = '<div class="ai-panel-loading" style="color:#C62828;">\u26A0 ' + _esc(err.message || 'Failed to connect to AI service') + '<br><br><button class="ai-btn-skip" style="border:1.5px solid #6B7280!important;padding:8px 16px;border-radius:6px;cursor:pointer;font-family:Calibri,sans-serif;">Close</button></div>';
    if (body2) body2.querySelector('.ai-btn-skip').addEventListener('click', _closePanel);
    var ctr3 = document.getElementById('ai-counter');
    if (ctr3) ctr3.textContent = 'Error';
  });
}

// ── Photo → Base64 Helper ───────────────────────────────
function _photoToBase64(photo) {
  return new Promise(function(resolve, reject) {
    if (photo.dataUrl && photo.dataUrl.indexOf('data:') === 0) {
      // Parse data URL: data:image/jpeg;base64,...
      var comma = photo.dataUrl.indexOf(',');
      var header = photo.dataUrl.substring(5, comma); // "image/jpeg;base64"
      var mediaType = header.split(';')[0];
      var data = photo.dataUrl.substring(comma + 1);
      resolve({ data: data, media_type: mediaType });
      return;
    }
    if (photo.r2Url) {
      fetch(photo.r2Url).then(function(res) {
        if (!res.ok) throw new Error('Failed to fetch photo: ' + res.status);
        return res.blob();
      }).then(function(blob) {
        var reader = new FileReader();
        reader.onload = function() {
          var result = reader.result;
          var comma = result.indexOf(',');
          var header = result.substring(5, comma);
          var mediaType = header.split(';')[0];
          var data = result.substring(comma + 1);
          resolve({ data: data, media_type: mediaType });
        };
        reader.onerror = function() { reject(new Error('FileReader failed')); };
        reader.readAsDataURL(blob);
      }).catch(reject);
      return;
    }
    reject(new Error('Photo has no dataUrl or r2Url'));
  });
}

// ── Photo Suggestion Modal ──────────────────────────────
function _showPhotoSuggestModal(state) {
  return new Promise(function(resolve) {
    var existing = document.getElementById('ai-ps-overlay');
    if (existing) existing.remove();

    var overlay = document.createElement('div');
    overlay.id = 'ai-ps-overlay';
    overlay.className = 'ai-fs-overlay';

    var html = '<div class="ai-fs-modal ai-ps-modal">';
    html += '<div class="ai-fs-header"><h3>\u2728 AI Photo Suggestion</h3>';
    html += '<button class="ai-ps-x" title="Close">\u2715</button></div>';
    html += '<div class="ai-ps-body" id="ai-ps-body">';
    html += '<div class="ai-panel-loading"><div class="ai-spinner"></div><br>Analyzing photo' + (state.photoCount > 1 ? 's' : '') + ' with Claude Sonnet\u2026</div>';
    html += '</div>';
    html += '<div class="ai-fs-footer ai-ps-footer" id="ai-ps-footer" style="display:none;">';
    html += '<span class="ai-ps-meta" id="ai-ps-meta"></span>';
    html += '<div class="ai-fs-btns">';
    html += '<button class="ai-fs-confirm" id="ai-ps-accept">Accept \u2192</button>';
    html += '<button class="ai-fs-cancel" id="ai-ps-dismiss">Dismiss</button>';
    html += '</div></div>';
    html += '</div>';
    overlay.innerHTML = html;
    document.body.appendChild(overlay);
    requestAnimationFrame(function() { overlay.classList.add('open'); });

    function cleanup(result) {
      overlay.classList.remove('open');
      setTimeout(function() { overlay.remove(); resolve(result); }, 150);
    }

    overlay.querySelector('.ai-ps-x').addEventListener('click', function() { cleanup(null); });

    // Expose update function on state object
    state.showResult = function(data) {
      var body = document.getElementById('ai-ps-body');
      var footer = document.getElementById('ai-ps-footer');
      var meta = document.getElementById('ai-ps-meta');
      if (!body) return;
      var confBadge = '';
      var confColor = data.confidence === 'high' ? '#1A7A4A' : (data.confidence === 'low' ? '#C0392B' : '#E67E22');
      confBadge = '<span style="display:inline-block;padding:2px 8px;border-radius:4px;background:' + confColor + ';color:white;font-size:calc(10px + var(--ts));font-weight:700;text-transform:uppercase;margin-left:8px;">' + _esc(data.confidence || 'medium') + ' confidence</span>';
      var notes = data.notes ? '<div class="ai-ps-notes">' + _esc(data.notes) + '</div>' : '';
      body.innerHTML = '<div class="ai-ps-suggestion-wrap">'
        + '<div class="ai-ps-label">SUGGESTED DESCRIPTION' + confBadge + '</div>'
        + '<textarea class="ai-ps-text" id="ai-ps-text">' + _esc(data.suggestion || '') + '</textarea>'
        + notes
        + '</div>';
      if (footer) footer.style.display = 'flex';
      if (meta && data.usage) {
        meta.textContent = 'Cost: $' + (data.usage.cost_usd || 0).toFixed(4);
      }
      var acceptBtn = document.getElementById('ai-ps-accept');
      if (acceptBtn) acceptBtn.addEventListener('click', function() {
        var ta = document.getElementById('ai-ps-text');
        cleanup({ accept: true, text: ta ? ta.value : (data.suggestion || '') });
      });
      var dismissBtn = document.getElementById('ai-ps-dismiss');
      if (dismissBtn) dismissBtn.addEventListener('click', function() { cleanup(null); });
    };

    state.showError = function(msg) {
      var body = document.getElementById('ai-ps-body');
      if (!body) return;
      body.innerHTML = '<div class="ai-panel-loading" style="color:#C62828;">\u26A0 ' + _esc(msg || 'Photo analysis failed') + '<br><br><button id="ai-ps-err-close" class="ai-fs-cancel">Close</button></div>';
      var btn = document.getElementById('ai-ps-err-close');
      if (btn) btn.addEventListener('click', function() { cleanup(null); });
    };
  });
}

// ── AI Suggest from Photos ──────────────────────────────
function suggestFromPhotos(opts) {
  // opts: { photos: [...], existingText: '...', onAccept: function(text) }
  if (!opts || !opts.photos || !opts.photos.length) {
    toast('\u26A0 No photos to analyze');
    return;
  }
  var token = _getToken();
  if (!token) { toast('\u26A0 AI Suggest requires cloud login'); return; }
  if (opts.photos.length > 4) {
    toast('\u26A0 Max 4 photos per suggestion');
    return;
  }

  var state = { photoCount: opts.photos.length };
  var modalPromise = _showPhotoSuggestModal(state);

  // Convert all photos to base64 in parallel
  Promise.all(opts.photos.map(_photoToBase64)).then(function(photoData) {
    var p = Model.getProject();
    var context = {
      tool: 'frt',
      projectNumber: (p && p.info && p.info.projectNumber) || '',
      projectName: (p && p.info && p.info.projectName) || ''
    };
    return fetch(WORKER_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'Authorization': 'Bearer ' + token },
      body: JSON.stringify({
        mode: 'photo_suggest',
        photos: photoData,
        existingText: opts.existingText || '',
        context: context
      })
    });
  }).then(function(res) {
    if (!res.ok) return res.json().then(function(e) { throw new Error(e.error || 'API error ' + res.status); });
    return res.json();
  }).then(function(data) {
    if (state.showResult) state.showResult(data);
  }).catch(function(err) {
    console.error('[AIAssist] Photo suggest error:', err);
    if (state.showError) state.showError(err.message || 'Failed to analyze photos');
  });

  modalPromise.then(function(result) {
    if (result && result.accept && opts.onAccept) {
      opts.onAccept(result.text);
    }
  });
}

// ── Dropdown Menu ───────────────────────────────────────
function _toggleMenu() {
  var m = document.getElementById('ai-mode-menu');
  if (m) m.classList.toggle('open');
}
function _closeMenu() {
  var m = document.getElementById('ai-mode-menu');
  if (m) m.classList.remove('open');
}

// ── Public API ──────────────────────────────────────────
export var AIAssist = {
  reviewAll: reviewAll,
  suggestFromPhotos: suggestFromPhotos,
  _toggleMenu: _toggleMenu,
  _closeMenu: _closeMenu
};

// Global access for onclick in HTML
window.AIAssist = AIAssist;
