/**
 * ARENCON FRT v2 — AI Writing Assistant
 * ══════════════════════════════════════
 * 
 * Collects text fields from FRT data model, sends to Cloudflare Worker
 * proxy → Anthropic API, shows review panel with diff view.
 * 
 * Modes:
 *   - 'rewrite' → Full rewrite using Sonnet (professional report language)
 *   - 'quickfix' → Quick fix using Haiku (typos & grammar only)
 */

import { Model } from '../data/model.js';
import { toast } from '../shared/toast.js';

var WORKER_URL = 'https://arencon-ai-worker.hezhendong999.workers.dev';
var _panel = null;
var _overlay = null;
var _suggestions = [];
var _fieldMap = {};
var _processed = 0;
var _accepted = 0;
var _busy = false;

function _esc(s) { return (s || '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;'); }

// ── Field Collection ────────────────────────────────────
function _collectFields() {
  var fields = [];
  _fieldMap = {};
  var p = Model.getProject();
  if (!p) return fields;
  var minLen = 8;

  // Contractor deficiencies
  (p.contractors || []).forEach(function(c, ci) {
    (c.deficiencies || []).forEach(function(d, di) {
      var dLabel = (c.name || 'General') + ' \u2192 #' + (d.num || '?');
      (d.observations || []).forEach(function(o, oi) {
        if (o.text && o.text.trim().length >= minLen) {
          var fid = 'c' + ci + '_d' + di + '_o' + oi;
          fields.push({ id: fid, label: dLabel + ' \u2192 Obs ' + (oi + 1), text: o.text.trim() });
          _fieldMap[fid] = { path: [ci, di, 'obs', oi], original: o.text.trim(), label: dLabel + ' \u2192 Obs ' + (oi + 1) };
        }
      });
      (d.activity || []).forEach(function(a, ai) {
        if (a.text && a.text.trim().length >= minLen && !a.autoGenerated) {
          var fid = 'c' + ci + '_d' + di + '_a' + ai;
          var aDate = a.date || '';
          fields.push({ id: fid, label: dLabel + ' \u2192 Activity ' + (aDate || (ai + 1)), text: a.text.trim() });
          _fieldMap[fid] = { path: [ci, di, 'act', ai], original: a.text.trim(), label: dLabel + ' \u2192 Activity ' + (aDate || (ai + 1)) };
        }
      });
      if (d.closedNote && d.closedNote.trim().length >= minLen) {
        var fid = 'c' + ci + '_d' + di + '_cn';
        fields.push({ id: fid, label: dLabel + ' \u2192 Closed Note', text: d.closedNote.trim() });
        _fieldMap[fid] = { path: [ci, di, 'cn', 0], original: d.closedNote.trim(), label: dLabel + ' \u2192 Closed Note' };
      }
    });
  });

  // General deficiencies
  (p.generalDeficiencies || []).forEach(function(d, di) {
    var dLabel = 'Site General \u2192 #' + (d.num || '?');
    (d.observations || []).forEach(function(o, oi) {
      if (o.text && o.text.trim().length >= minLen) {
        var fid = 'g' + di + '_o' + oi;
        fields.push({ id: fid, label: dLabel + ' \u2192 Obs ' + (oi + 1), text: o.text.trim() });
        _fieldMap[fid] = { path: ['gen', di, 'obs', oi], original: o.text.trim(), label: dLabel + ' \u2192 Obs ' + (oi + 1) };
      }
    });
    (d.activity || []).forEach(function(a, ai) {
      if (a.text && a.text.trim().length >= minLen && !a.autoGenerated) {
        var fid = 'g' + di + '_a' + ai;
        fields.push({ id: fid, label: dLabel + ' \u2192 Activity ' + (a.date || (ai + 1)), text: a.text.trim() });
        _fieldMap[fid] = { path: ['gen', di, 'act', ai], original: a.text.trim(), label: dLabel + ' \u2192 Activity ' + (a.date || (ai + 1)) };
      }
    });
  });

  return fields;
}

// ── Word-Level Diff (LCS algorithm) ─────────────────────
function _wordDiff(original, improved) {
  if (original === improved) return { html: _esc(improved), changed: false };
  var a = original.split(/(\s+)/), b = improved.split(/(\s+)/);
  var m = a.length, n = b.length;
  if (m > 200 || n > 200) {
    return { html: '<span class="ai-diff-del">' + _esc(original) + '</span> <span class="ai-diff-add">' + _esc(improved) + '</span>', changed: true };
  }
  var dp = [];
  for (var i = 0; i <= m; i++) { dp[i] = []; for (var j = 0; j <= n; j++) dp[i][j] = 0; }
  for (i = 1; i <= m; i++) for (j = 1; j <= n; j++) {
    if (a[i - 1] === b[j - 1]) dp[i][j] = dp[i - 1][j - 1] + 1;
    else dp[i][j] = Math.max(dp[i - 1][j], dp[i][j - 1]);
  }
  var result = [];
  i = m; j = n;
  while (i > 0 || j > 0) {
    if (i > 0 && j > 0 && a[i - 1] === b[j - 1]) {
      result.unshift({ type: 'same', text: a[i - 1] }); i--; j--;
    } else if (j > 0 && (i === 0 || dp[i][j - 1] >= dp[i - 1][j])) {
      result.unshift({ type: 'add', text: b[j - 1] }); j--;
    } else {
      result.unshift({ type: 'del', text: a[i - 1] }); i--;
    }
  }
  var html = '';
  result.forEach(function(r) {
    if (r.type === 'same') html += _esc(r.text);
    else if (r.type === 'add') html += '<span class="ai-diff-add">' + _esc(r.text) + '</span>';
    else html += '<span class="ai-diff-del">' + _esc(r.text) + '</span>';
  });
  return { html: html, changed: true };
}

// ── Panel UI ────────────────────────────────────────────
function _ensurePanel() {
  if (_panel) return;
  _overlay = document.createElement('div');
  _overlay.className = 'ai-panel-overlay';
  _overlay.addEventListener('click', function() { _closePanel(); });
  document.body.appendChild(_overlay);

  _panel = document.createElement('div');
  _panel.className = 'ai-panel';
  _panel.addEventListener('click', function(e) { e.stopPropagation(); });
  _panel.innerHTML = '<div class="ai-panel-hdr"><h3>\u2728 AI Review</h3><div class="ai-panel-hdr-btns">'
    + '<button class="ai-btn-accept-all" id="ai-accept-all"style="background:#1A7A4A;color:white;">Accept All</button>'
    + '<button class="ai-btn-close" style="background:rgba(255,255,255,.15);color:white;">\u2715</button>'
    + '</div></div>'
    + '<div class="ai-panel-counter" id="ai-counter"></div>'
    + '<div class="ai-panel-body" id="ai-body"></div>';
  document.body.appendChild(_panel);

  // Wire panel buttons
  _panel.querySelector('.ai-btn-close').addEventListener('click', _closePanel);
  _panel.querySelector('#ai-accept-all').addEventListener('click', _acceptAll);
}

function _openPanel() {
  _ensurePanel();
  requestAnimationFrame(function() {
    _overlay.classList.add('open');
    _panel.classList.add('open');
  });
}

function _closePanel() {
  if (_overlay) _overlay.classList.remove('open');
  if (_panel) _panel.classList.remove('open');
  if (_accepted > 0) {
    Model.saveNow();
    Model._notify('project', Model.getProject());
  }
  _busy = false;
  _updateBtn(false);
}

function _updateCounter() {
  var el = document.getElementById('ai-counter');
  if (!el) return;
  var total = _suggestions.length;
  var remaining = total - _processed;
  if (remaining <= 0) el.textContent = '\u2714 All done \u2014 ' + _accepted + ' accepted, ' + (total - _accepted) + ' skipped';
  else el.textContent = (_processed + 1) + ' of ' + total + ' suggestions';
}

function _renderSuggestions(suggestions) {
  _suggestions = suggestions.filter(function(s) {
    var fm = _fieldMap[s.id];
    return fm && s.improved && s.improved !== fm.original;
  });
  _processed = 0;
  _accepted = 0;
  var body = document.getElementById('ai-body');
  if (!body) return;
  body.innerHTML = '';
  if (_suggestions.length === 0) {
    body.innerHTML = '<div class="ai-panel-done">\u2714 All text looks good \u2014 no suggestions</div>';
    _updateCounter();
    var aaBtn = document.getElementById('ai-accept-all');
    if (aaBtn) aaBtn.style.display = 'none';
    setTimeout(function() { _closePanel(); }, 3000);
    return;
  }
  var aaBtn2 = document.getElementById('ai-accept-all');
  if (aaBtn2) aaBtn2.style.display = '';

  _suggestions.forEach(function(s, idx) {
    var fm = _fieldMap[s.id];
    if (!fm) return;
    var diff = _wordDiff(fm.original, s.improved);
    var div = document.createElement('div');
    div.className = 'ai-suggestion';
    div.id = 'ai-sug-' + idx;
    div.innerHTML = '<div class="ai-field-label">' + _esc(fm.label) + '</div>'
      + '<div class="ai-text-box-label">Original</div>'
      + '<div class="ai-text-box">' + _esc(fm.original) + '</div>'
      + '<div class="ai-text-box-label">Suggested</div>'
      + '<div class="ai-text-box">' + diff.html + '</div>'
      + (s.changes && s.changes !== 'no changes needed' ? '<div class="ai-changes-note">' + _esc(s.changes) + '</div>' : '')
      + '<div class="ai-suggestion-btns">'
      + '<button class="ai-btn-accept" data-sug-idx="' + idx + '">Accept</button>'
      + '<button class="ai-btn-skip" data-sug-idx="' + idx + '">Skip</button>'
      + '</div>';
    body.appendChild(div);
  });

  // Delegate accept/skip clicks
  body.addEventListener('click', function(e) {
    var btn = e.target.closest && e.target.closest('[data-sug-idx]');
    if (!btn) return;
    var idx = parseInt(btn.getAttribute('data-sug-idx'));
    if (btn.classList.contains('ai-btn-accept')) _accept(idx);
    else if (btn.classList.contains('ai-btn-skip')) _skip(idx);
  });

  _updateCounter();
}

// ── Accept / Skip / Accept All ──────────────────────────
function _accept(idx) {
  var s = _suggestions[idx];
  if (!s) return;
  var fm = _fieldMap[s.id];
  if (!fm) return;
  _writeBack(fm.path, s.improved);
  Model.saveNow();
  var el = document.getElementById('ai-sug-' + idx);
  if (el) {
    el.classList.add('processed');
    var btns = el.querySelector('.ai-suggestion-btns');
    if (btns) btns.innerHTML = '<span style="color:#1A7A4A;font-weight:600;">\u2714 Accepted</span>';
  }
  _processed++;
  _accepted++;
  _updateCounter();
  _scrollToNext(idx);
  if (_processed >= _suggestions.length) _finishReview();
}

function _skip(idx) {
  var el = document.getElementById('ai-sug-' + idx);
  if (el) {
    el.classList.add('processed');
    var btns = el.querySelector('.ai-suggestion-btns');
    if (btns) btns.innerHTML = '<span style="color:#6B7280;">Skipped</span>';
  }
  _processed++;
  _updateCounter();
  _scrollToNext(idx);
  if (_processed >= _suggestions.length) _finishReview();
}

function _acceptAll() {
  _suggestions.forEach(function(s, idx) {
    var el = document.getElementById('ai-sug-' + idx);
    if (el && !el.classList.contains('processed')) _accept(idx);
  });
}

function _scrollToNext(currentIdx) {
  for (var i = currentIdx + 1; i < _suggestions.length; i++) {
    var el = document.getElementById('ai-sug-' + i);
    if (el && !el.classList.contains('processed')) {
      el.scrollIntoView({ behavior: 'smooth', block: 'start' });
      return;
    }
  }
}

function _finishReview() {
  if (_accepted > 0) {
    Model.saveNow();
    Model._notify('project', Model.getProject());
  }
  _updateCounter();
  setTimeout(function() { _closePanel(); }, 2500);
}

// ── Write-Back to Data Model ────────────────────────────
function _writeBack(path, newText) {
  var p = Model.getProject();
  if (!p) return;
  var ci = path[0], di = path[1], type = path[2], idx = path[3];
  var deficArr;
  if (ci === 'gen') {
    deficArr = p.generalDeficiencies;
  } else {
    if (!p.contractors || !p.contractors[ci]) return;
    deficArr = p.contractors[ci].deficiencies;
  }
  if (!deficArr || !deficArr[di]) return;
  var d = deficArr[di];
  if (type === 'obs') {
    if (d.observations && d.observations[idx]) { d.observations[idx].text = newText; d.observations[idx].aiReviewed = true; }
    if (d.entries && d.entries[idx]) { d.entries[idx].text = newText; d.entries[idx].description = newText; }
    if (idx === 0) d.description = newText;
  } else if (type === 'act') {
    if (d.activity && d.activity[idx]) { d.activity[idx].text = newText; d.activity[idx].aiReviewed = true; }
  } else if (type === 'cn') {
    d.closedNote = newText; d.closedNoteAiReviewed = true;
  }
}

// ── Button State ────────────────────────────────────────
function _updateBtn(busy, mode) {
  var btn = document.getElementById('btn-ai-review');
  if (!btn) return;
  if (busy) {
    btn.disabled = true;
    btn.innerHTML = '<span class="ai-spin-icon">\u2728</span> ' + (mode === 'quickfix' ? 'Checking' : 'Rewriting') + '\u2026';
  } else {
    btn.disabled = false;
    btn.innerHTML = '\u2728 AI Review \u25BE';
  }
}

// ── Auth Token ──────────────────────────────────────────
function _getToken() {
  return localStorage.getItem('sb-access-token') || null;
}

// ── Field Selector Modal ────────────────────────────────
function _showFieldSelector(fields, mode) {
  return new Promise(function(resolve) {
    var existing = document.getElementById('ai-fs-overlay');
    if (existing) existing.remove();

    var overlay = document.createElement('div');
    overlay.id = 'ai-fs-overlay';
    overlay.className = 'ai-fs-overlay';

    var modeLabel = mode === 'quickfix' ? 'Quick Fix (Haiku)' : 'Full Rewrite (Sonnet)';

    // Group fields by deficiency for nicer display
    var html = '<div class="ai-fs-modal">';
    html += '<div class="ai-fs-header"><h3>\u2728 AI Review \u2014 Select Fields</h3>';
    html += '<button class="ai-fs-x" title="Cancel">\u2715</button></div>';
    html += '<div class="ai-fs-subhdr"><span class="ai-fs-mode">' + _esc(modeLabel) + '</span>';
    html += '<button class="ai-fs-toggle" data-state="all">Deselect All</button></div>';
    html += '<div class="ai-fs-body">';
    fields.forEach(function(f, i) {
      var text = f.text || '';
      var preview = text.length > 140 ? text.substring(0, 140) + '\u2026' : text;
      html += '<label class="ai-fs-row">';
      html += '<input type="checkbox" class="ai-fs-check" data-idx="' + i + '" checked>';
      html += '<div class="ai-fs-info">';
      html += '<div class="ai-fs-label">' + _esc(f.label) + '</div>';
      html += '<div class="ai-fs-preview">' + _esc(preview) + '</div>';
      html += '</div></label>';
    });
    html += '</div>';
    html += '<div class="ai-fs-footer"><span class="ai-fs-count">' + fields.length + ' of ' + fields.length + ' selected</span>';
    html += '<div class="ai-fs-btns"><button class="ai-fs-confirm">Review \u2192</button>';
    html += '<button class="ai-fs-cancel">Cancel</button></div></div>';
    html += '</div>';
    overlay.innerHTML = html;
    document.body.appendChild(overlay);
    requestAnimationFrame(function() { overlay.classList.add('open'); });

    function updateCount() {
      var checks = overlay.querySelectorAll('.ai-fs-check');
      var cnt = 0;
      for (var i = 0; i < checks.length; i++) if (checks[i].checked) cnt++;
      var span = overlay.querySelector('.ai-fs-count');
      if (span) span.textContent = cnt + ' of ' + fields.length + ' selected';
      var btn = overlay.querySelector('.ai-fs-confirm');
      if (btn) {
        btn.disabled = cnt === 0;
        btn.textContent = 'Review ' + cnt + ' \u2192';
      }
      var toggle = overlay.querySelector('.ai-fs-toggle');
      if (toggle) {
        var allOn = cnt === fields.length;
        toggle.textContent = allOn ? 'Deselect All' : 'Select All';
        toggle.dataset.state = allOn ? 'all' : 'none';
      }
    }

    overlay.addEventListener('change', function(e) {
      if (e.target.classList && e.target.classList.contains('ai-fs-check')) updateCount();
    });

    overlay.querySelector('.ai-fs-toggle').addEventListener('click', function() {
      var checks = overlay.querySelectorAll('.ai-fs-check');
      var allOn = true;
      for (var i = 0; i < checks.length; i++) if (!checks[i].checked) { allOn = false; break; }
      for (var j = 0; j < checks.length; j++) checks[j].checked = !allOn;
      updateCount();
    });

    function cleanup(result) {
      overlay.classList.remove('open');
      setTimeout(function() { overlay.remove(); resolve(result); }, 150);
    }

    overlay.querySelector('.ai-fs-x').addEventListener('click', function() { cleanup(null); });
    overlay.querySelector('.ai-fs-cancel').addEventListener('click', function() { cleanup(null); });
    overlay.querySelector('.ai-fs-confirm').addEventListener('click', function() {
      var selected = [];
      var checks = overlay.querySelectorAll('.ai-fs-check');
      for (var i = 0; i < checks.length; i++) {
        if (checks[i].checked) {
          var idx = parseInt(checks[i].getAttribute('data-idx'), 10);
          selected.push(fields[idx]);
        }
      }
      cleanup(selected.length > 0 ? selected : null);
    });
    updateCount();
  });
}

// ── Main Entry Point ────────────────────────────────────
function reviewAll(mode) {
  if (_busy) return;
  if (!mode) mode = 'rewrite';
  if (!Model.getProject()) { toast('\u26A0 Open a project first'); return; }
  var token = _getToken();
  if (!token) { toast('\u26A0 AI Review requires cloud login'); return; }
  var allFields = _collectFields();
  if (allFields.length === 0) { toast('\u2714 No text fields to review'); return; }

  // Show field selector for >1 field; single field auto-proceeds
  if (allFields.length === 1) {
    _doReview(allFields, mode, token);
    return;
  }
  _showFieldSelector(allFields, mode).then(function(selected) {
    if (!selected || selected.length === 0) return; // cancelled
    _doReview(selected, mode, token);
  });
}

function _doReview(fields, mode, token) {
  _busy = true;
  _updateBtn(true, mode);
  _openPanel();

  var body = document.getElementById('ai-body');
  var modeLabel = mode === 'quickfix' ? 'Quick Fix (Haiku)' : 'Full Rewrite (Sonnet)';
  if (body) body.innerHTML = '<div class="ai-panel-loading"><div class="ai-spinner"></div><br>' + modeLabel + '<br>Reviewing ' + fields.length + ' field' + (fields.length !== 1 ? 's' : '') + '\u2026</div>';
  var aaBtn = document.getElementById('ai-accept-all');
  if (aaBtn) aaBtn.style.display = 'none';
  var ctr = document.getElementById('ai-counter');
  if (ctr) ctr.textContent = modeLabel + ' \u2014 Sending\u2026';

  var p = Model.getProject();
  var context = {
    tool: 'frt',
    projectNumber: (p.info && p.info.projectNumber) || '',
    projectName: (p.info && p.info.projectName) || ''
  };

  fetch(WORKER_URL, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'Authorization': 'Bearer ' + token },
    body: JSON.stringify({ fields: fields, context: context, mode: mode })
  })
  .then(function(res) {
    if (!res.ok) return res.json().then(function(e) { throw new Error(e.error || 'API error ' + res.status); });
    return res.json();
  })
  .then(function(data) {
    _busy = false;
    _updateBtn(false);
    if (!data.suggestions || !Array.isArray(data.suggestions)) {
      throw new Error('Invalid response from AI');
    }
    _renderSuggestions(data.suggestions);
    if (data.usage && data.usage.cost_usd !== undefined) {
      var ctr2 = document.getElementById('ai-counter');
      if (ctr2) ctr2.textContent += (' \u00B7 Cost: $' + data.usage.cost_usd.toFixed(4));
    }
  })
  .catch(function(err) {
    _busy = false;
    _updateBtn(false);
    console.error('[AIAssist] Error:', err);
    var body2 = document.getElementById('ai-body');
    if (body2) body2.innerHTML = '<div class="ai-panel-loading" style="color:#C62828;">\u26A0 ' + _esc(err.message || 'Failed to connect to AI service') + '<br><br><button class="ai-btn-skip" style="border:1.5px solid #6B7280!important;padding:8px 16px;border-radius:6px;cursor:pointer;font-family:Calibri,sans-serif;">Close</button></div>';
    if (body2) body2.querySelector('.ai-btn-skip').addEventListener('click', _closePanel);
    var ctr3 = document.getElementById('ai-counter');
    if (ctr3) ctr3.textContent = 'Error';
  });
}

// ── Photo → Base64 Helper ───────────────────────────────
function _photoToBase64(photo) {
  return new Promise(function(resolve, reject) {
    if (photo.dataUrl && photo.dataUrl.indexOf('data:') === 0) {
      // Parse data URL: data:image/jpeg;base64,...
      var comma = photo.dataUrl.indexOf(',');
      var header = photo.dataUrl.substring(5, comma); // "image/jpeg;base64"
      var mediaType = header.split(';')[0];
      var data = photo.dataUrl.substring(comma + 1);
      resolve({ data: data, media_type: mediaType });
      return;
    }
    if (photo.r2Url) {
      fetch(photo.r2Url).then(function(res) {
        if (!res.ok) throw new Error('Failed to fetch photo: ' + res.status);
        return res.blob();
      }).then(function(blob) {
        var reader = new FileReader();
        reader.onload = function() {
          var result = reader.result;
          var comma = result.indexOf(',');
          var header = result.substring(5, comma);
          var mediaType = header.split(';')[0];
          var data = result.substring(comma + 1);
          resolve({ data: data, media_type: mediaType });
        };
        reader.onerror = function() { reject(new Error('FileReader failed')); };
        reader.readAsDataURL(blob);
      }).catch(reject);
      return;
    }
    reject(new Error('Photo has no dataUrl or r2Url'));
  });
}

// ── Photo Suggestion Modal ──────────────────────────────
function _showPhotoSuggestModal(state) {
  return new Promise(function(resolve) {
    var existing = document.getElementById('ai-ps-overlay');
    if (existing) existing.remove();

    var overlay = document.createElement('div');
    overlay.id = 'ai-ps-overlay';
    overlay.className = 'ai-fs-overlay';

    var html = '<div class="ai-fs-modal ai-ps-modal">';
    html += '<div class="ai-fs-header"><h3>\u2728 AI Photo Suggestion</h3>';
    html += '<button class="ai-ps-x" title="Close">\u2715</button></div>';
    html += '<div class="ai-ps-body" id="ai-ps-body">';
    html += '<div class="ai-panel-loading"><div class="ai-spinner"></div><br>Analyzing photo' + (state.photoCount > 1 ? 's' : '') + ' with Claude Sonnet\u2026</div>';
    html += '</div>';
    html += '<div class="ai-fs-footer ai-ps-footer" id="ai-ps-footer" style="display:none;">';
    html += '<span class="ai-ps-meta" id="ai-ps-meta"></span>';
    html += '<div class="ai-fs-btns">';
    html += '<button class="ai-fs-confirm" id="ai-ps-accept">Accept \u2192</button>';
    html += '<button class="ai-fs-cancel" id="ai-ps-dismiss">Dismiss</button>';
    html += '</div></div>';
    html += '</div>';
    overlay.innerHTML = html;
    document.body.appendChild(overlay);
    requestAnimationFrame(function() { overlay.classList.add('open'); });

    function cleanup(result) {
      overlay.classList.remove('open');
      setTimeout(function() { overlay.remove(); resolve(result); }, 150);
    }

    overlay.querySelector('.ai-ps-x').addEventListener('click', function() { cleanup(null); });

    // Expose update function on state object
    state.showResult = function(data) {
      var body = document.getElementById('ai-ps-body');
      var footer = document.getElementById('ai-ps-footer');
      var meta = document.getElementById('ai-ps-meta');
      if (!body) return;
      var confBadge = '';
      var confColor = data.confidence === 'high' ? '#1A7A4A' : (data.confidence === 'low' ? '#C0392B' : '#E67E22');
      confBadge = '<span style="display:inline-block;padding:2px 8px;border-radius:4px;background:' + confColor + ';color:white;font-size:calc(10px + var(--ts));font-weight:700;text-transform:uppercase;margin-left:8px;">' + _esc(data.confidence || 'medium') + ' confidence</span>';
      var notes = data.notes ? '<div class="ai-ps-notes">' + _esc(data.notes) + '</div>' : '';
      body.innerHTML = '<div class="ai-ps-suggestion-wrap">'
        + '<div class="ai-ps-label">SUGGESTED DESCRIPTION' + confBadge + '</div>'
        + '<textarea class="ai-ps-text" id="ai-ps-text">' + _esc(data.suggestion || '') + '</textarea>'
        + notes
        + '</div>';
      if (footer) footer.style.display = 'flex';
      if (meta && data.usage) {
        meta.textContent = 'Cost: $' + (data.usage.cost_usd || 0).toFixed(4);
      }
      var acceptBtn = document.getElementById('ai-ps-accept');
      if (acceptBtn) acceptBtn.addEventListener('click', function() {
        var ta = document.getElementById('ai-ps-text');
        cleanup({ accept: true, text: ta ? ta.value : (data.suggestion || '') });
      });
      var dismissBtn = document.getElementById('ai-ps-dismiss');
      if (dismissBtn) dismissBtn.addEventListener('click', function() { cleanup(null); });
    };

    state.showError = function(msg) {
      var body = document.getElementById('ai-ps-body');
      if (!body) return;
      body.innerHTML = '<div class="ai-panel-loading" style="color:#C62828;">\u26A0 ' + _esc(msg || 'Photo analysis failed') + '<br><br><button id="ai-ps-err-close" class="ai-fs-cancel">Close</button></div>';
      var btn = document.getElementById('ai-ps-err-close');
      if (btn) btn.addEventListener('click', function() { cleanup(null); });
    };
  });
}

// ── AI Suggest from Photos ──────────────────────────────
function suggestFromPhotos(opts) {
  // opts: { photos: [...], existingText: '...', onAccept: function(text) }
  if (!opts || !opts.photos || !opts.photos.length) {
    toast('\u26A0 No photos to analyze');
    return;
  }
  var token = _getToken();
  if (!token) { toast('\u26A0 AI Suggest requires cloud login'); return; }
  if (opts.photos.length > 4) {
    toast('\u26A0 Max 4 photos per suggestion');
    return;
  }

  var state = { photoCount: opts.photos.length };
  var modalPromise = _showPhotoSuggestModal(state);

  // Convert all photos to base64 in parallel
  Promise.all(opts.photos.map(_photoToBase64)).then(function(photoData) {
    var p = Model.getProject();
    var context = {
      tool: 'frt',
      projectNumber: (p && p.info && p.info.projectNumber) || '',
      projectName: (p && p.info && p.info.projectName) || ''
    };
    return fetch(WORKER_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'Authorization': 'Bearer ' + token },
      body: JSON.stringify({
        mode: 'photo_suggest',
        photos: photoData,
        existingText: opts.existingText || '',
        context: context
      })
    });
  }).then(function(res) {
    if (!res.ok) return res.json().then(function(e) { throw new Error(e.error || 'API error ' + res.status); });
    return res.json();
  }).then(function(data) {
    if (state.showResult) state.showResult(data);
  }).catch(function(err) {
    console.error('[AIAssist] Photo suggest error:', err);
    if (state.showError) state.showError(err.message || 'Failed to analyze photos');
  });

  modalPromise.then(function(result) {
    if (result && result.accept && opts.onAccept) {
      opts.onAccept(result.text);
    }
  });
}

// ── Dropdown Menu ───────────────────────────────────────
function _toggleMenu() {
  var m = document.getElementById('ai-mode-menu');
  if (m) m.classList.toggle('open');
}
function _closeMenu() {
  var m = document.getElementById('ai-mode-menu');
  if (m) m.classList.remove('open');
}

// ── Public API ──────────────────────────────────────────
export var AIAssist = {
  reviewAll: reviewAll,
  suggestFromPhotos: suggestFromPhotos,
  // S114 P1.6 — inline scratchpad ↓
  openScratchpadFromPhoto: openScratchpadFromPhoto,
  openScratchpadFromAllPhotos: openScratchpadFromAllPhotos,
  aiReviewPin: aiReviewPin,
  shortenScratchpad: shortenScratchpad,
  shortenUserText: shortenUserText,
  mergeScratchpad: mergeScratchpad,
  discardScratchpad: discardScratchpad,
  scratchpadHasContent: function(deficId, obsIdx) { return _spHasContent(deficId, obsIdx); },
  scratchpadGet: function(deficId, obsIdx) { return _spState[_spKey(deficId, obsIdx)] || null; },
  scratchpadEdit: function(deficId, obsIdx, newText) {
    var s = _spState[_spKey(deficId, obsIdx)];
    if (s) s.text = newText;
  },
  repopulateAllScratchpads: function() {
    Object.keys(_spState).forEach(function(k) {
      var lastColon = k.lastIndexOf(':');
      if (lastColon < 0) return;
      var did = k.substring(0, lastColon);
      var oIdx = parseInt(k.substring(lastColon + 1));
      _spRender(did, oIdx);
    });
  },
  _toggleMenu: _toggleMenu,
  _closeMenu: _closeMenu
};

// ── S114 P1.6 — Inline AI Scratchpad ────────────────────
// Per-observation persistent scratchpad. Multi-photo accumulation, three merge
// actions (Insert/Append/Replace via execCommand for native Ctrl+Z), Shorten
// (twice — for AI text in scratchpad, and for user text in textarea).
// State key format: "<deficId>:<obsIdx>" (deficId can contain ':' from UUID,
// so we split from the right when parsing).
var _spState = {};

function _spKey(deficId, obsIdx) { return deficId + ':' + obsIdx; }
function _spGet(deficId, obsIdx) {
  var k = _spKey(deficId, obsIdx);
  if (!_spState[k]) _spState[k] = {
    text: '', photoIds: [], loading: false, error: null,
    costTotal: 0, confidence: null, photoCount: 0,
    noOp: false, noOpReason: ''
  };
  return _spState[k];
}
function _spClear(deficId, obsIdx) { delete _spState[_spKey(deficId, obsIdx)]; }
function _spHasContent(deficId, obsIdx) {
  var s = _spState[_spKey(deficId, obsIdx)];
  return !!(s && (s.text || s.loading || s.error || s.noOp));
}

function _ctx() {
  var p = Model.getProject();
  return {
    tool: 'frt',
    projectNumber: (p && p.info && p.info.projectNumber) || '',
    projectName: (p && p.info && p.info.projectName) || ''
  };
}

// Find or create the scratchpad container inside the matching observation block.
function _spContainer(deficId, obsIdx) {
  var sel = '.ai-scratchpad[data-sp-defic="' + deficId + '"][data-sp-obs="' + obsIdx + '"]';
  return document.querySelector(sel);
}

function _spRender(deficId, obsIdx) {
  var el = _spContainer(deficId, obsIdx);
  if (!el) return; // not visible (other tab, collapsed, etc.)
  var s = _spState[_spKey(deficId, obsIdx)];
  if (!s) { el.style.display = 'none'; el.innerHTML = ''; return; }
  el.style.display = 'block';

  var meta = '';
  if (s.metaLabel) meta = _esc(s.metaLabel);
  else if (s.photoCount > 0) meta = 'from ' + s.photoCount + ' photo' + (s.photoCount === 1 ? '' : 's');
  if (s.confidence) {
    var cColor = s.confidence === 'high' ? '#1A7A4A' : (s.confidence === 'low' ? '#C0392B' : '#E67E22');
    meta += '<span class="ai-sp-conf" style="background:' + cColor + ';">' + _esc(s.confidence) + '</span>';
  }
  if (s.costTotal > 0) meta += '<span class="ai-sp-cost">$' + s.costTotal.toFixed(4) + '</span>';

  var html = '<div class="ai-sp-header">'
    + '<span class="ai-sp-title">\u2728 AI scratchpad <span class="ai-sp-meta">' + meta + '</span></span>'
    + '<button class="ai-sp-x" data-action="ai-sp-discard" data-defic-id="' + _esc(deficId) + '" data-obs-idx="' + obsIdx + '" title="Discard">\u2715</button>'
    + '</div>';

  if (s.loading) {
    html += '<div class="ai-sp-loading"><div class="ai-spinner"></div> Analyzing\u2026</div>';
  } else if (s.error) {
    html += '<div class="ai-sp-error">\u26A0 ' + _esc(s.error) + '</div>';
    html += '<div class="ai-sp-footer"><button class="ai-sp-btn" data-action="ai-sp-discard" data-defic-id="' + _esc(deficId) + '" data-obs-idx="' + obsIdx + '">Close</button></div>';
  } else if (s.noOp) {
    // S117 hotfix: AI reviewed the text and confirmed no changes needed.
    // This is a SUCCESS state — surface it positively (not as the empty
    // placeholder, which reads like "did nothing").
    html += '<div class="ai-sp-noop" style="padding:14px 12px;color:#1A7A4A;font-weight:600;display:flex;align-items:center;gap:8px;">\u2714 Text already looks professional \u2014 no changes needed</div>';
    if (s.noOpReason && s.noOpReason !== 'No changes needed' && s.noOpReason.toLowerCase().indexOf('no change') < 0) {
      html += '<div style="padding:0 12px 10px;color:#6B7B8C;font-size:calc(11px + var(--ts));">' + _esc(s.noOpReason) + '</div>';
    }
    html += '<div class="ai-sp-footer"><button class="ai-sp-btn" data-action="ai-sp-discard" data-defic-id="' + _esc(deficId) + '" data-obs-idx="' + obsIdx + '">Close</button></div>';
  } else if (s.text) {
    html += '<textarea class="ai-sp-text" data-action="ai-sp-edit" data-defic-id="' + _esc(deficId) + '" data-obs-idx="' + obsIdx + '" placeholder="AI suggestion will appear here\u2026">' + _esc(s.text) + '</textarea>';
    html += '<div class="ai-sp-footer">';
    html += '<button class="ai-sp-btn ai-sp-primary" data-action="ai-sp-insert" data-defic-id="' + _esc(deficId) + '" data-obs-idx="' + obsIdx + '" title="Insert at cursor (or replace selection) in your description">\u2328\uFE0F Insert at cursor</button>';
    html += '<button class="ai-sp-btn" data-action="ai-sp-append" data-defic-id="' + _esc(deficId) + '" data-obs-idx="' + obsIdx + '" title="Append after your existing description">\u2935\uFE0F Append below</button>';
    html += '<button class="ai-sp-btn" data-action="ai-sp-replace" data-defic-id="' + _esc(deficId) + '" data-obs-idx="' + obsIdx + '" title="Replace your description entirely (Ctrl+Z to undo)">\u21C4 Replace all</button>';
    html += '<span class="ai-sp-sep"></span>';
    html += '<button class="ai-sp-btn ai-sp-secondary" data-action="ai-sp-shorten" data-defic-id="' + _esc(deficId) + '" data-obs-idx="' + obsIdx + '" title="Shorten this AI text without losing meaning">\u2702\uFE0F Shorten</button>';
    html += '</div>';
  } else {
    html += '<div class="ai-sp-loading">Open by clicking \u2728 on a photo.</div>';
  }
  el.innerHTML = html;
}

// Send a single photo to the worker. If scratchpad already has text, append the
// AI's response with a separator. If not, scratchpad starts fresh.
function openScratchpadFromPhoto(deficId, obsIdx, photoIdx) {
  var f = Model.findDeficiency(deficId);
  if (!f) { toast('\u26A0 Deficiency not found'); return; }
  var obs = f.defic.observations && f.defic.observations[obsIdx];
  if (!obs || !obs.photos || !obs.photos[photoIdx]) { toast('\u26A0 Photo not found'); return; }
  var photo = obs.photos[photoIdx];
  var s = _spGet(deficId, obsIdx);
  if (s.loading) { toast('\u26A0 Already analyzing\u2026'); return; }
  // Prevent double-counting the same photo in accumulation
  if (s.photoIds.indexOf(photo.id) >= 0) {
    toast('\u26A0 Photo ' + (photoIdx + 1) + ' already in scratchpad');
    return;
  }
  var token = _getToken();
  if (!token) { toast('\u26A0 AI requires cloud login'); return; }

  s.loading = true; s.error = null;
  _spRender(deficId, obsIdx);

  _photoToBase64(photo).then(function(pd) {
    return fetch(WORKER_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'Authorization': 'Bearer ' + token },
      body: JSON.stringify({ mode: 'photo_suggest', photos: [pd], existingText: '', context: _ctx() })
    });
  }).then(function(r) {
    if (!r.ok) return r.json().then(function(e) { throw new Error(e.error || 'API error ' + r.status); });
    return r.json();
  }).then(function(data) {
    s.loading = false;
    var newText = data.suggestion || '';
    if (s.text) {
      s.text = s.text + '\n\n\u2014 Photo ' + (photoIdx + 1) + ' \u2014\n' + newText;
    } else {
      s.text = newText;
    }
    s.photoIds.push(photo.id);
    s.photoCount = s.photoIds.length;
    if (data.usage && typeof data.usage.cost_usd === 'number') s.costTotal += data.usage.cost_usd;
    s.confidence = data.confidence || s.confidence;
    _spRender(deficId, obsIdx);
  }).catch(function(err) {
    s.loading = false;
    s.error = err.message || 'Failed to analyze photo';
    _spRender(deficId, obsIdx);
  });
}

// Synthesis: replace scratchpad with one coherent description from up to 4 photos
// (Worker's per-call limit). Photos beyond 4 get a toast notice.
function openScratchpadFromAllPhotos(deficId, obsIdx) {
  var f = Model.findDeficiency(deficId);
  if (!f) { toast('\u26A0 Deficiency not found'); return; }
  var obs = f.defic.observations && f.defic.observations[obsIdx];
  if (!obs || !obs.photos || !obs.photos.length) { toast('\u26A0 No photos on this observation'); return; }
  var photos = obs.photos.slice(0, 4);
  var skipped = obs.photos.length - photos.length;
  var s = _spGet(deficId, obsIdx);
  if (s.loading) { toast('\u26A0 Already analyzing\u2026'); return; }
  var token = _getToken();
  if (!token) { toast('\u26A0 AI requires cloud login'); return; }

  s.loading = true; s.error = null;
  _spRender(deficId, obsIdx);

  Promise.all(photos.map(_photoToBase64)).then(function(pds) {
    return fetch(WORKER_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'Authorization': 'Bearer ' + token },
      body: JSON.stringify({ mode: 'photo_suggest', photos: pds, existingText: '', context: _ctx() })
    });
  }).then(function(r) {
    if (!r.ok) return r.json().then(function(e) { throw new Error(e.error || 'API error ' + r.status); });
    return r.json();
  }).then(function(data) {
    s.loading = false;
    try { console.log('[AIAssist] photo_suggest response:', JSON.stringify(data).slice(0, 800)); } catch(_){}
    s.text = data.suggestion || '';
    if (!s.text) {
      s.error = 'AI returned no description for these photos. Check console for details.';
      _spRender(deficId, obsIdx);
      return;
    }
    s.photoIds = photos.map(function(p) { return p.id; });
    s.photoCount = s.photoIds.length;
    if (data.usage && typeof data.usage.cost_usd === 'number') s.costTotal += data.usage.cost_usd;
    s.confidence = data.confidence || null;
    _spRender(deficId, obsIdx);
    if (skipped > 0) toast('\u26A0 Used first 4 of ' + obs.photos.length + ' photos (' + skipped + ' over Worker limit)');
  }).catch(function(err) {
    s.loading = false;
    try { console.error('[AIAssist] photo_suggest failed:', err); } catch(_){}
    s.error = err.message || 'Failed to analyze photos';
    _spRender(deficId, obsIdx);
  });
}

// Shorten the scratchpad text in-place. Sends current scratchpad content to
// Worker with mode='shorten' and replaces scratchpad.
function shortenScratchpad(deficId, obsIdx) {
  var s = _spState[_spKey(deficId, obsIdx)];
  if (!s || !s.text || s.loading) return;
  var token = _getToken();
  if (!token) { toast('\u26A0 AI requires cloud login'); return; }
  var origText = s.text;
  s.loading = true;
  _spRender(deficId, obsIdx);
  fetch(WORKER_URL, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'Authorization': 'Bearer ' + token },
    body: JSON.stringify({
      fields: [{ path: 'scratchpad', name: 'AI Scratchpad', value: origText }],
      mode: 'shorten',
      context: _ctx()
    })
  }).then(function(r) {
    if (!r.ok) return r.json().then(function(e) { throw new Error(e.error || 'API error ' + r.status); });
    return r.json();
  }).then(function(data) {
    s.loading = false;
    try { console.log('[AIAssist] shortenScratchpad response:', JSON.stringify(data).slice(0, 800)); } catch(_){}
    var sug = data.suggestions && data.suggestions[0];
    var shortText = sug ? (sug.improved || sug.suggestion || '') : '';
    if (shortText && shortText !== origText) {
      s.text = shortText;
    } else {
      // Worker said no change / returned same text — keep original, surface
      // a transient toast so user knows the call succeeded.
      toast('\u2714 Already concise \u2014 no shortening needed');
    }
    if (data.usage && typeof data.usage.cost_usd === 'number') s.costTotal += data.usage.cost_usd;
    _spRender(deficId, obsIdx);
  }).catch(function(err) {
    s.loading = false;
    try { console.error('[AIAssist] shortenScratchpad failed:', err); } catch(_){}
    s.error = err.message || 'Shorten failed';
    _spRender(deficId, obsIdx);
  });
}

// Shorten the user's description text in the textarea (or just the selection).
// Uses execCommand('insertText') so Ctrl+Z reverts.
function shortenUserText(deficId, obsIdx) {
  var ta = document.querySelector('textarea[data-action="obs-text"][data-defic-id="' + deficId + '"][data-obs-idx="' + obsIdx + '"]');
  if (!ta) { toast('\u26A0 Textarea not found'); return; }
  var hasSelection = ta.selectionStart !== ta.selectionEnd;
  var startSel = ta.selectionStart, endSel = ta.selectionEnd;
  var fullText = ta.value;
  var textToShorten = hasSelection ? fullText.substring(startSel, endSel) : fullText;
  if (!textToShorten.trim()) { toast('\u26A0 Nothing to shorten'); return; }
  var token = _getToken();
  if (!token) { toast('\u26A0 AI requires cloud login'); return; }

  toast('\u2702\uFE0F Shortening\u2026');
  fetch(WORKER_URL, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'Authorization': 'Bearer ' + token },
    body: JSON.stringify({
      fields: [{ path: 'usertext', name: 'Description', value: textToShorten }],
      mode: 'shorten',
      context: _ctx()
    })
  }).then(function(r) {
    if (!r.ok) return r.json().then(function(e) { throw new Error(e.error || 'API error ' + r.status); });
    return r.json();
  }).then(function(data) {
    try { console.log('[AIAssist] shortenUserText response:', JSON.stringify(data).slice(0, 800)); } catch(_){}
    var sug = data.suggestions && data.suggestions[0];
    var shortText = sug ? (sug.improved || sug.suggestion || '') : '';
    var changesNote = sug ? String(sug.changes || '').toLowerCase() : '';
    if (!shortText || shortText === textToShorten) {
      if (changesNote.indexOf('no change') >= 0 || changesNote.indexOf('already') >= 0) {
        toast('\u2714 Already concise \u2014 no shortening needed');
      } else {
        toast('\u26A0 No suggestion returned \u2014 see console');
      }
      return;
    }
    ta.focus();
    if (hasSelection) ta.setSelectionRange(startSel, endSel);
    else ta.setSelectionRange(0, ta.value.length);
    document.execCommand('insertText', false, shortText);
    // Trigger input event so Model.updateObservation runs and saves
    ta.dispatchEvent(new Event('input', { bubbles: true }));
    toast('\u2714 Shortened (Ctrl+Z to undo)');
  }).catch(function(err) {
    try { console.error('[AIAssist] shortenUserText failed:', err); } catch(_){}
    toast('\u26A0 Shorten failed: ' + (err.message || ''));
  });
}

// Merge scratchpad text into the user's textarea via execCommand so native Ctrl+Z works.
// mode: 'insert' = at caret (replaces current selection if any)
//       'append' = at end of textarea, two-newline gap
//       'replace' = entire textarea replaced
function mergeScratchpad(deficId, obsIdx, mode) {
  var s = _spState[_spKey(deficId, obsIdx)];
  if (!s || !s.text) { toast('\u26A0 Nothing in scratchpad to merge'); return; }
  var ta = document.querySelector('textarea[data-action="obs-text"][data-defic-id="' + deficId + '"][data-obs-idx="' + obsIdx + '"]');
  if (!ta) { toast('\u26A0 Textarea not found'); return; }

  ta.focus();
  if (mode === 'insert') {
    // Replaces current selection (or inserts at caret if no selection)
    document.execCommand('insertText', false, s.text);
  } else if (mode === 'append') {
    var endPos = ta.value.length;
    ta.setSelectionRange(endPos, endPos);
    var prefix = (ta.value && !/\n\n$/.test(ta.value)) ? '\n\n' : '';
    document.execCommand('insertText', false, prefix + s.text);
  } else if (mode === 'replace') {
    ta.setSelectionRange(0, ta.value.length);
    document.execCommand('insertText', false, s.text);
  }
  ta.dispatchEvent(new Event('input', { bubbles: true }));
  var label = mode === 'insert' ? 'Inserted at cursor'
    : mode === 'append' ? 'Appended below'
    : 'Replaced description';
  toast('\u2714 ' + label + ' (Ctrl+Z to undo)');
}

function discardScratchpad(deficId, obsIdx) {
  _spClear(deficId, obsIdx);
  _spRender(deficId, obsIdx);
}

// S114 P1.8: per-pin AI Review entry point. mode = 'photos' | 'rewrite' | 'quickfix'.
// 'photos' delegates to openScratchpadFromAllPhotos. Text modes call the existing
// fields-based review endpoint and pipe the result into obs 0's scratchpad.
function aiReviewPin(deficId, mode) {
  var f = Model.findDeficiency(deficId);
  if (!f) { toast('\u26A0 Pin not found'); return; }
  var obsIdx = 0; // primary observation
  var obs = f.defic.observations && f.defic.observations[obsIdx];
  if (!obs) { toast('\u26A0 No observation on this pin'); return; }

  if (mode === 'photos') {
    if (!(obs.photos || []).length) {
      toast('\u26A0 No photos on this pin \u2014 use Text only or Quick review');
      return;
    }
    openScratchpadFromAllPhotos(deficId, obsIdx);
    return;
  }

  // Text-only modes
  var origText = (obs.text || '').trim();
  if (!origText) { toast('\u26A0 No text to review'); return; }
  var s = _spGet(deficId, obsIdx);
  if (s.loading) { toast('\u26A0 Already analyzing\u2026'); return; }
  var token = _getToken();
  if (!token) { toast('\u26A0 AI requires cloud login'); return; }

  s.loading = true; s.error = null;
  s.metaLabel = mode === 'rewrite' ? 'full text review' : 'quick review';
  _spRender(deficId, obsIdx);

  fetch(WORKER_URL, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'Authorization': 'Bearer ' + token },
    body: JSON.stringify({
      fields: [{ path: 'observation', name: 'Observation', value: origText }],
      mode: mode,
      context: _ctx()
    })
  }).then(function(r) {
    if (!r.ok) return r.json().then(function(e) { throw new Error(e.error || 'API error ' + r.status); });
    return r.json();
  }).then(function(data) {
    s.loading = false;
    // S117 hotfix: log full response so any future "no suggestion" cases
    // can be diagnosed by reading the browser console instead of guessing.
    try { console.log('[AIAssist] aiReviewPin response:', mode, JSON.stringify(data).slice(0, 800)); } catch(_){}
    var sug = data.suggestions && data.suggestions[0];
    var newText = sug ? (sug.improved || sug.suggestion || '') : '';
    var changesNote = sug ? String(sug.changes || '').toLowerCase() : '';
    var aiSaidNoChanges = changesNote.indexOf('no change') >= 0
                       || changesNote.indexOf('unchanged') >= 0
                       || changesNote.indexOf('no edit') >= 0
                       || changesNote.indexOf('already') >= 0;

    if (!newText && aiSaidNoChanges) {
      // S117 hotfix: AI confirmed the text is already polished. Show this
      // as a positive state (not an error). User keeps their original text;
      // we surface a small "✔ no changes needed" message in the scratchpad
      // so they know the review actually ran.
      s.text = '';
      s.noOp = true;
      s.noOpReason = sug.changes || 'No changes needed';
      if (data.usage && typeof data.usage.cost_usd === 'number') s.costTotal += data.usage.cost_usd;
      _spRender(deficId, obsIdx);
      return;
    }

    if (!newText) {
      // Genuine empty response — fall back to original text so user can
      // see SOMETHING actionable and surface a diagnostic message.
      s.error = 'AI returned an empty response. Check console for details.';
      _spRender(deficId, obsIdx);
      return;
    }

    s.text = newText;
    s.noOp = false;
    s.photoIds = []; s.photoCount = 0;
    if (data.usage && typeof data.usage.cost_usd === 'number') s.costTotal += data.usage.cost_usd;
    s.confidence = sug && sug.confidence ? sug.confidence : null;
    _spRender(deficId, obsIdx);
  }).catch(function(err) {
    s.loading = false;
    try { console.error('[AIAssist] aiReviewPin failed:', err); } catch(_){}
    s.error = err.message || 'Review failed';
    _spRender(deficId, obsIdx);
  });
}

// Global access for onclick in HTML
window.AIAssist = AIAssist;
